version: '3'
services:
  client_app:
    build: ./client_Proxy
    ports:
      - "8080:8080"
    container_name: app_cleint
    volumes:
      - "./public/swagger.json:/client_app/public/swagger.json"
      - ".env:/client_app/.env"
  server_rpc:
    build: ./server_rpc
    ports:
      - "1234:1234"
    container_name: server_rpc
    volumes:
      - ".env:/server_app/.env"

  db:
    image: postgres:14.4-alpine
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    ports:
        - "5432:5432"
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"